name: build/release vsix package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: |
          npm install -g @vscode/vsce
      - name: Build package
        run: vsce package
      - name: Release
        if: startsWith(github.ref, 'refs/tags')
        run: |
          awk -v ver=${{ github.ref_name }} '/^## Version / { if (p) { exit }; if ($3 == ver) { p=1; next } } p && NF' CHANGELOG.md > RELEASE_NOTES
          gh release create ${{ github.ref_name }} -F RELEASE_NOTES *.vsix
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
